### ISSUE TITLE
broken dependency golang.org/x/exp/inotify

### ISSUE THREAD

**Issue by turbomettwurst** [dullgiulio/perso#2]
currently building fails to due to:
package golang.org/x/exp/inotify: no buildable Go source files in ~/build/.go/src/golang.org/x/exp/inotify
It seems inotify is no longer and it should be replaced with gopkg.in/fsnotify.v0 instead.

**Comment by dullgiulio** [comment]
Thanks a lot! If you want to provide a patch, I'll merge it. Otherwise I'll do it myself in the next days.

**Comment by turbomettwurst** [comment]
unfortunately i lack the required qualifications to do so..
i can give it a try, but that's a bit like a monkey with a typewriter.. :-)

**Comment by dullgiulio** [comment]
Thanks a lot for figuring out what to do about this. Sorry for the long wait, I have fixed the build for linux.
