### ISSUE TITLE
perso returns a 404 to every request

### ISSUE THREAD

**Issue by turbomettwurst** [dullgiulio/perso#4]
i tried running perso on to two Linux Machines (with the same Maildir copied over)
In both Cases it returns:
```
$ curl -i hostname.domain.net:8888/latest/0/
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 23 Jan 2017 08:17:03 GMT
Content-Length: 19

404 page not found

```
One Machine is a rather old Suse Linux Enterprise Server, the other one is my current Machine running Arch Linux. Both show the same behaviour but no errors or warnings are given.
Any Recommendations on how to get/provide useful debugging info?

**Comment by dullgiulio** [comment]
Might also be a regression after the last changes.

What is the command line command you use to start perso? Any output?

Make sure to run with the full path of the maildir mailbox, as in:

$ ls /var/mail/someuser
new cur tmp
$ perso /var/mail/someuser

**Comment by turbomettwurst** [comment]
Ahhh, the relative path was my mistake. Works beautifully when given a full path!

Thx a lot!
