### ISSUE TITLE
ability to delete Messages

### ISSUE THREAD

**Issue by turbomettwurst** [dullgiulio/perso#5]
i tried to delete individual Messages from my Maildir by running:
curl -X DELETE http://hostname:8888/latest/0

Unfortunately perso wasn't overly impressed by my attempts and chose to simply act as if i had send a GET and simply responded with the content of 0.
Is deletion simply not implemented or am i doing something wrong?

**Comment by dullgiulio** [comment]
This is currently not implemented. In fact I didn't even think about it, as we use this exclusively to read messages.

But I suppose it's a nice feature request. One could even include PUT...

**Comment by turbomettwurst** [comment]
Yes one could! :-)
I for one would love that feature, will gladly pay for the first days beer!

**Comment by dullgiulio** [comment]
I'll work on it. No promises, but will land soon.

**Comment by dullgiulio** [comment]
Sorry for the long wait, paid work got in the way.

It should work as expected now. Be careful and of course no responsibility on my side it / was removed ;)

**Comment by turbomettwurst** [comment]
Awesome! :-)
Will give it a shot tomorrow!

**Comment by turbomettwurst** [comment]
Works like a charm, thx again. <3
